#include <iostream>
#include <memory>
#include <vector>
#include <cmath>

#include <verilated.h>
#include <verilated_vcd_c.h>
#include "VDSP_Subsystem.h" // The header generated by Verilator

vluint64_t main_time = 0; // Global simulation time

class SimulatedEngine {
private:
    VDSP_Subsystem* dut;
    
    bool last_adc_clk = false;
    int sample_counter = 0;

public:
    SimulatedEngine(VDSP_Subsystem* dut_ptr): dut(dut_ptr) {}

    // Generate audio samples (e.g. an impulse to test IIR filter response)
    void drive_adc_input() {
        // Detect rising edge of ADC clock
        if (dut->adc_cic_clk && !last_adc_clk) {
            if (dut->adc_ready_out) {
                // Send an impulse on sample 10, otherwise 0
                int32_t simulated_audio = (sample_counter == 10) ? 10000 : 0;
                
                dut->adc_valid_in = (sample_counter < 50); // Stop feeding after 50 samples
                dut->adc_data_in = simulated_audio;
                
                if (dut->adc_valid_in) {
                    std::cout << "[ADC] Sent Sample " << sample_counter << ": " << simulated_audio << std::endl;
                }
                sample_counter++;
            }
        }
        last_adc_clk = dut->adc_cic_clk;
    }

    // Sink AXI-Stream Output on sys_clk rising edge
    void monitor_axis_output(bool sys_clk_rising_edge) {
        // Randomly backpressure the AXI stream to test the async FIFO and stall logic
        dut->m_axis_tready = (rand() % 10 > 2); // 70% of the time ready
        
        if (sys_clk_rising_edge) {
            if (dut->m_axis_tvalid && dut->m_axis_tready) {
                int32_t filtered_data = dut->m_axis_tdata_out;
                std::cout << "[AXIS DMA] Received Filtered Data: " << filtered_data;
                if (dut->m_axis_tlast) {
                    std::cout << " [LAST BEAT OF BURST]";
                }
                std::cout << std::endl;
            }
        }
    }
};

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv); 
    Verilated::traceEverOn(true);       

    VDSP_Subsystem* dut = new VDSP_Subsystem;       
    VerilatedVcdC* tfp = new VerilatedVcdC; 
    SimulatedEngine engine(dut);
    
    dut->trace(tfp, 99);                
    tfp->open("waveform_top.vcd");          

    // Reset Phase
    dut->rst_n = 0;
    dut->sys_clk = 0;
    dut->adc_cic_clk = 0;
    
    // Advance time to clear reset
    for(int i=0; i<20; i++) {
        dut->sys_clk = !dut->sys_clk;
        dut->adc_cic_clk = !dut->adc_cic_clk;
        dut->eval();
        tfp->dump(main_time++);
    }
    
    dut->rst_n = 1;
    std::cout << "--- Reset lifted, starting DSP processing ---" << std::endl;

    // Main Simulation Loop with separate clock domains
    // sys_clk = fast (e.g. 50MHz) -> toggles every 2 units
    // adc_cic_clk = slow (e.g. 10MHz) -> toggles every 10 units
    for(int i = 0; i < 2000; i++) {
        bool sys_clk_rising_edge = false;

        if (main_time % 2 == 0) {
            dut->sys_clk = !dut->sys_clk;
            sys_clk_rising_edge = dut->sys_clk;
        }
        if (main_time % 10 == 0) {
            dut->adc_cic_clk = !dut->adc_cic_clk;
        }
        
        dut->eval();
        
        engine.drive_adc_input();
        engine.monitor_axis_output(sys_clk_rising_edge);
        
        tfp->dump(main_time++);
    } 

    std::cout << "Simulation Completed" << std::endl;

    dut->final();
    tfp->close();
    delete dut;
    delete tfp;
    return 0;
}